---
title: "101-demulti"
author: "Mac Campbell"
date: "1/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
```

## Barcodes

Barcodes appear to be reverse complemented.    
want:
id      seq     style      
D708_508        TAATGCGC-GTACTGAC       TruSeq   
D709_501        CGGCTATG-TATAGCCT       TruSeq   
D709_502        CGGCTATG-ATAGAGGC       TruSeq   


```{r}
df<-read_csv("sequenced-fish/samples-barcodes-01042022.csv")
```

```{r}
d15<-df %>% filter(`library number`=="SOMM515") %>% select(`Sample name`, Barcode)
write_tsv(d15, "demultiplex/somm515.tsv", col_names = FALSE)

d16<-df %>% filter(`library number`=="SOMM516") %>% select(`Sample name`, Barcode)
write_tsv(d16, "demultiplex/somm516.tsv", col_names = FALSE)

d17<-df %>% filter(`library number`=="SOMM517") %>% select(`Sample name`, Barcode)
write_tsv(d17, "demultiplex/somm517.tsv", col_names = FALSE)

```


Trying in screen:    

```{sh, eval=FALSE}

module load fastq-multx 

srun -p production -t 1-01:00:0 

$HOME/fastq-multx/fastq-multx -m 0 -B demultiplex/somm515.tsv \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM515/SOMM515_S1_L001_I1_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM515/SOMM515_S1_L001_I2_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM515/SOMM515_S1_L001_R1_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM515/SOMM515_S1_L001_R2_001.fastq.gz \
-o n/a -o n/a \
-o /share/schreierlab/smelt-wgs/demulti-SOMM515/%_R1.fastq.gz \
-o /share/schreierlab/smelt-wgs/demulti-SOMM515/%_R2.fastq.gz

srun -p production -t 0-12:00:0 
$HOME/fastq-multx/fastq-multx -m 0 -B demultiplex/somm516.tsv \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM516/SOMM516_S1_L002_I1_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM516/SOMM516_S1_L002_I2_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM516/SOMM516_S1_L002_R1_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM516/SOMM516_S1_L002_R2_001.fastq.gz \
-o n/a -o n/a \
-o /share/schreierlab/smelt-wgs/demulti-SOMM516/%_R1.fastq.gz \
-o /share/schreierlab/smelt-wgs/demulti-SOMM516/%_R2.fastq.gz

srun -p production -t 0-12:00:0 fastq-multx -m 0 -B demultiplex/somm517.tsv \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM517/SOMM517_S1_L003_I1_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM517/SOMM517_S1_L003_I2_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM517/SOMM517_S1_L003_R1_001.fastq.gz \
/share/schreierlab/smelt-wgs/Project_AFSR_SOMM517/SOMM517_S1_L003_R2_001.fastq.gz \
-o n/a -o n/a \
-o /share/schreierlab/smelt-wgs/demulti-SOMM517/%_R1.fastq.gz \
-o /share/schreierlab/smelt-wgs/demulti-SOMM517/%_R2.fastq.gz

```


SOMM517 ran to completion

Ran all to completion!!

