---
title: "1301-with-family-info"
output: html_document
date: "2023-09-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r}
library(tidyverse)
library(viridis)
library(data.table)
library(ggrepel)
library(RcppCNPy)
```

## Get family data 

Tag ID may/may not have leading zero. Thats annoying.
```{r}
family<-read_csv("parentage/tidy-family-data.csv")
family$`Offspring Tag ID`<-gsub("_0","_",family$`Offspring Tag ID`)
family<-family %>% group_by(`Offspring Tag ID`) %>% mutate(Count=n()) %>% filter(Count<2)

```

## Get basic meta


```{r}
keepers<-read_tsv("bamlists/test96.bamlist", col_names = c("Path"))
keepers$SeqFile<-gsub("/home/maccamp/dsm-omics/data/SOMM\\d+/","",keepers$Path)
keepers$Sample<-gsub("_R1.*","",keepers$SeqFile)
keepers<-keepers %>% separate(Sample, into=c("CrossType","Tank","Individual"),remove = FALSE, sep="_")
keepers<-keepers %>% mutate(DI=ifelse(str_detect(Sample, '^h|^H'), "HighDI",
                               ifelse(str_detect(Sample, '^l|^L'), "LowDI", "Epi")))
keepers$Type<-gsub("Low","L",keepers$DI)
keepers$Type<-gsub("High","H",keepers$Type)
keepers
```

`

```{r}
pcseqs<-keepers
cov<-read_delim("outputs/601/chroms.cov", col_names=FALSE, delim=" ") %>% as.matrix()
```


```{r}
#' @param samples character vector with the individuals IDs in the order in which
#' they were passed in the bamlist to angsd.
#' @param cov covariance matrix
covar2pcs <- function(samples, cov) {
  
  
  eig <- eigen(cov, symm = TRUE)
  PC <- as.data.frame(eig$vectors) %>%
    as_tibble() %>%
    setNames(sprintf("PC-%02d", 1:ncol(.)))
  
  samtib <- tibble(sample = samples)
  
  list(
    PCs = bind_cols(samtib, PC),
    eigevalues = eig$values
  )
}

```

```{r}
pca <- covar2pcs(pcseqs$Sample, cov)

pca_long <- pca$PCs %>%
  tidyr::gather(., key = "PC", "val", -sample)

# then expand a grid of the possible comparisons (ordered)
expg <- expand.grid(sample = pca$PCs$sample,
                    PCx = sprintf("PC-%02d", 1:6),
                    PCy = sprintf("PC-%02d", 1:6),
                    stringsAsFactors = FALSE) %>%
  tibble::as_tibble()

# then left join the pca results onto that
pca_pairs <- dplyr::left_join(expg, pca_long, by = c("sample", "PCx" = "PC")) %>%
  dplyr::rename(val_x = val) %>%
  dplyr::left_join(pca_long, by = c("sample", "PCy" = "PC")) %>%
  dplyr::rename(val_y = val)

pp_meta <- pca_pairs %>%   # just keep the first 6 PCs around
  left_join(., pcseqs, by = c("sample" = "Sample")) 

npc <- 4
pp_meta2 <- pp_meta %>%
  filter( (PCx %in% sprintf("PC-%02d", 1:npc)) & 
            (PCy %in% sprintf("PC-%02d", 1:npc)) )

eig <- eigen(cov, symm = TRUE)
var<-eig$values/sum(eig$values)
cumvar<-cumsum(eig$values)/sum(eig$values)


ggplot(pp_meta2) +
  geom_point(aes(x=val_x, y=val_y, color=DI)) +
  coord_fixed() +
  facet_grid (PCx ~ PCy)

```

```{r}

sub12<-pp_meta2 %>% filter(PCx=="PC-01") %>% filter(PCy=="PC-02")


pc12<-ggplot(sub12, aes(x = val_x, y = val_y, fill = Type, shape=Type)) +
  geom_point(size = 4, alpha=0.75) +
  scale_fill_discrete(na.value = "white") + 
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = ""))+
  ylab(paste("PC2", " ", round((100*var[2]),2), "%", sep = ""))+
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_viridis_d() +
  scale_shape_manual(values=c(21,24))

pc12

ggsave("outputs/1301/pc12.jpeg")
```

```{r}
sub13<-pp_meta2 %>% filter(PCx=="PC-01") %>% filter(PCy=="PC-03")


pc13<-ggplot(sub13, aes(x = val_x, y = val_y, color = Family)) +
  geom_point(size = 2, alpha=0.75) +
  scale_fill_discrete(na.value = "white") + 
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = ""))+
  ylab(paste("PC3", " ", round((100*var[3]),2), "%", sep = ""))+
  ggtitle("PCs 1 & 3")+
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_viridis_d(option="H") +
  facet_wrap(.~BroodYear)
  
pc13

```


```{r}
ggplot(sub12, aes(x = val_x, y = val_x, color = Family, shape=CrossType)) +
  geom_point(size = 2, alpha=0.75) +
  scale_fill_discrete(na.value = "white") + 
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC1", " ", round((100*var[1]),2), "%", sep = ""))+
  ylab(paste("PC1", " ", round((100*var[1]),2), "%", sep = ""))+
  ggtitle("PCs 1 & 1")+
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_viridis_d(option="H") +
  facet_wrap(.~Family)
```


```{r}
ggplot(sub12, aes(x = val_y, y = val_y, color = Family, shape=CrossType)) +
  geom_point(size = 2, alpha=0.75) +
  scale_fill_discrete(na.value = "white") + 
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC2", " ", round((100*var[2]),2), "%", sep = ""))+
  ylab(paste("PC2", " ", round((100*var[2]),2), "%", sep = ""))+
  ggtitle("PCs 2 & 2")+
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_viridis_d(option="H")  +
  facet_wrap(.~Family)
```


```{r}
ggplot(sub13, aes(x = val_y, y = val_y, color = Family)) +
  geom_point(size = 2, alpha=0.75) +
  scale_fill_discrete(na.value = "white") + 
  theme_bw()+
  theme(panel.grid=element_blank())+
  xlab(paste("PC3", " ", round((100*var[3]),2), "%", sep = ""))+
  ylab(paste("PC3", " ", round((100*var[3]),2), "%", sep = ""))+
  ggtitle("PCs 3 & 3")+
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_colour_viridis_d(option="H")  +
  facet_wrap(.~Family)
```