---
title: "701-Fst"
author: "Mac Campbell"
date: "6/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r}
library(tidyverse)
```

## Fst

Fst looks to be a good place to start.    

```{sh, eval=FALSE}
srun -p bigmemh -t 2-12:00:00 --mem=32G --nodes=1 $HOME/angsd/angsd -b bamlists/testHDI.bamlist -anc $HOME/genomes/GCF021917145.1/GCF_021917145.1_fHypTra1_genomic.fna \
  -ref $HOME/genomes/GCF021917145.1/GCF_021917145.1_fHypTra1_genomic.fna \
  -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -baq 2 -GL 1  -doMaf 1 -doMajorMinor 1 \
  -minMapQ 20 -minQ 20 -doSaf 1 -nThreads 8  \
  -minInd 38 -nind 42 -out outputs/701/hdi > outputs/701/hdi.stdout 2> outputs/701/hdi.stderr &
  
srun -p med -t 2-12:00:00 --mem=32G --nodes=1 $HOME/angsd/angsd -b bamlists/testLDI.bamlist -anc $HOME/genomes/GCF021917145.1/GCF_021917145.1_fHypTra1_genomic.fna \
  -ref $HOME/genomes/GCF021917145.1/GCF_021917145.1_fHypTra1_genomic.fna \
  -uniqueOnly 1 -remove_bads 1 -only_proper_pairs 1 -baq 2 -GL 1  -doMaf 1 -doMajorMinor 1 \
  -minMapQ 20 -minQ 20 -doSaf 1 -nThreads 8  \
  -minInd 44 -nind 49 -out outputs/701/ldi > outputs/701/ldi.stdout 2> outputs/701/ldi.stderr &
  
```

Commands like this:

```{sh, eval=FALSE}
realSFS outputs/701/hdi.saf.idx >  outputs/701/hdi.sfs
realSFS outputs/701/ldi.saf.idx >  outputs/701/ldi.sfs
realSFS outputs/701/hdi.saf.idx outputs/701/ldi.saf.idx > outputs/701/hdi-ldi.2dsfs
realSFS fst index  outputs/701/hdi.saf.idx  outputs/701/ldi.saf.idx -sfs outputs/701/hdi-ldi.2dsfs -fstout outputs/701/hdi-ldi
realSFS fst stats outputs/701/hdi-ldi.fst.idx > outputs/701/hdi-ldi.fst.stats
```
